# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-20 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reviews", "0002_auto_20181020_0931")]

    operations = [
        migrations.RenameField(
            model_name="company", old_name="account", new_name="user"
        )
    ]
