# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-21 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("reviews", "0003_auto_20181020_1428")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
