# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-05 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reviews", "0006_auto_20190408_0831")]

    operations = [
        migrations.AlterModelOptions(
            name="company", options={"verbose_name_plural": "Companies"}
        ),
        migrations.AlterModelOptions(
            name="product", options={"verbose_name_plural": "Products"}
        ),
        migrations.AlterModelOptions(
            name="review", options={"verbose_name_plural": "Reviews"}
        ),
    ]
